[package]
name = "massping"
version = "0.2.2"
edition = "2021"
license = "MIT"
description = "ICMP ping library for sending batches of ICMP echo request packets and measuring the roundtrip time"
keywords = ["icmp", "ping"]
categories = ["network-programming"]
repository = "https://github.com/M4SS-Code/massping"
readme = "README.md"
rust-version = "1.64"

[dependencies]
pnet_packet = "0.31"
socket2 = "0.4"

getrandom = "0.2"
tokio = { version = "1.14", features = ["net", "sync", "rt"] }

# weak
libc = "0.2"

# stream
futures-core = { version = "0.3", optional = true }

[dev-dependencies]
tokio = { version = "1.14", features = ["macros", "time"] }
futures-util = { version = "0.3", default-features = false }

[features]
default = ["strong", "stream"]
strong = []
stream = ["dep:futures-core"]
