[package]
name = "massping"
version = "0.1.3"
edition = "2021"
license = "MIT"
description = "ICMP ping library for sending batches of ICMP echo request packets and measuring the roundtrip time"
keywords = ["icmp", "ping"]
categories = ["network-programming"]
repository = "https://github.com/M4SS-Code/massping"
readme = "README.md"
rust-version = "1.56"

[dependencies]
pnet_packet = "0.29"
pnet_transport = "0.29"
tokio = { version = "1", features = ["rt"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt"] }
