[package]
name = "massping"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "ICMP ping library for sending batches of ICMP echo request packets and measuring the roundtrip time"
keywords = ["icmp", "ping"]
categories = ["network-programming"]
repository = "https://github.com/M4SS-Code/massping"
readme = "README.md"
rust-version = "1.56"

[dependencies]
pnet_packet = "0.30"
pnet_transport = "0.30"
getrandom = "0.2"
tokio = { version = "1.14", features = ["macros", "rt", "sync"] }
