[package]
name = "fastping-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
pnet = "0.28"
tokio = { version = "1", features = ["rt"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt"] }
