[package]
name = "massping"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "ICMP ping library for sending batches of ICMP echo request packets and measuring the roundtrip time"
repository = "https://github.com/M4SS-Code/massping"
readme = "README.md"

[dependencies]
pnet = "0.28"
tokio = { version = "1", features = ["rt"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt"] }
