name: CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_UNSTABLE_SPARSE_REGISTRY: true

jobs:
  fmt:
    name: rustfmt / stable
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - run: rustup component add rustfmt

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: clippy / nightly
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - run: rustup component add clippy

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  test:
    name: test / ${{ matrix.name }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          #- name: stable
          #  rust: stable
          #- name: beta
          #  rust: beta
          - name: nightly
            rust: nightly
          #- name: MSRV 1.64
          #  rust: 1.64

    steps:
      - uses: actions/checkout@v2

      - run: sudo $HOME/.cargo/bin/rustup default ${{ matrix.rust }}

      - run: sudo env "PATH=$PATH" CI=1 $HOME/.cargo/bin/cargo test
